### ISSUE TITLE
Allow HTML Tags in Code Snippet

### ISSUE THREAD

**Issue by taufik-nurrohman** [scrivo/highlight.php#62] opened 2020-01-24 10:23 UTC
The reason I use _highlight.js_ in my blog was because it allows me to preserve HTML tags inside the code snippet. Knowing that there is a _highlight.php_ project makes everything so perfect! But one thing is missing; that is the ability to retain HTML tags inside the code snippet. I used to add `<mark>` tags to explain to my readers about the important parts, and maybe some `<a>` tags to link some piece of code to the documentation page.

How do I keep the HTML markup in my code snippet? Disabling the &ldquo;safe mode&rdquo; does not work for me. It always throws _&ldquo;\`self\` is not supported at the top-level of a language.&rdquo;_ message anyway.

By the way, I have used your project to complete my content management system extension [here](https://mecha-cms.com/store/extension/highlight). This project fits my environment so well :+1:

Thanks.

**Comment by allejo** [comment] 2020-01-24 16:20
Could you provide a snippet with your HTML tags that works in highlight.js but not highlight.php? And if you could provide a snippet that breaks with safe mode disabled too, that'd be great!

If one snippet meets both requirements, then that's fine too! This way I can debug where the differences in behavior are.

> By the way, I have used your project to complete my content management system extension [here](https://mecha-cms.com/store/extension/highlight). This project fits my environment so well 👍

This makes me very happy to hear! :smile:

**Comment by taufik-nurrohman** [comment] 2020-01-25 11:16
With _highlight.js_, it is possible to mark the custom elements across token:

![IMG_20200125_175807](https://user-images.githubusercontent.com/1669261/73120124-e81ec480-3f9c-11ea-93c0-c0d3ede172de.jpg)

&rarr; http://jsfiddle.net/toubia95/bDW8H

With _highlight.php_, it gets encoded:

![IMG_20200125_175744](https://user-images.githubusercontent.com/1669261/73120136-01c00c00-3f9d-11ea-88f3-55713754e52d.jpg)

&rarr; https://mecha-cms.com/store/extension/t-o-c

**Comment by allejo** [comment] 2020-01-26 04:07
Executing `highlight()` in both highlight.js and highlight.php (without using something like `<mark>` return the same result:

**Code to highlight**

```text
// fonction pour créer un objet date
function gjsCreerObjetDate(jour, mois, annee) {
    return new Date(annee, mois - 1, jour);
}
```

**highlight.php**

```html
<span class="hljs-comment">// fonction pour créer un objet date</span>
<span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">gjsCreerObjetDate</span>(<span class="hljs-params">jour, mois, annee</span>) </span>{
    <span class="hljs-keyword">return</span> <span class="hljs-keyword">new</span> <span class="hljs-built_in">Date</span>(annee, mois - <span class="hljs-number">1</span>, jour);
}
```

**highlight.js**

```html
<span class="hljs-comment">// fonction pour créer un objet date</span>
<span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">gjsCreerObjetDate</span>(<span class="hljs-params">jour, mois, annee</span>) </span>{
    <span class="hljs-keyword">return</span> <span class="hljs-keyword">new</span> <span class="hljs-built_in">Date</span>(annee, mois - <span class="hljs-number">1</span>, jour);
}
```

In your JSFiddle, you are using `highlightBlock`, which does not have an equivalent in highlight.php. `highlightBlock` has special behavior to handle the DOM and leave HTML alone; it's why you must escape HTML if you want highlight.js to highlight HMTL.

In the following example, I'll use `<mark>` to see the different behaviors.

**highlight.php with `<mark>`**

Even though it doesn't match highlight.js behavior, `highlight()` in highlight.php is working as intended here, in my opinion.

```php
$hl = new Highlighter();
$text = <<<CODE
// fonction pour créer un objet date
function gjsCreer<mark>ObjetDate(jo</mark>ur, mois, annee) {
    return new Date(annee, mois - 1, jour);
}
CODE;

echo $hl->highlight('javascript', $text)->value;
```

```html
<span class="hljs-comment">// fonction pour créer un objet date</span>
<span class="hljs-function"><span class="hljs-keyword">function</span> <span class="hljs-title">gjsCreer</span>&lt;<span class="hljs-title">mark</span>&gt;<span class="hljs-title">ObjetDate</span>(<span class="hljs-params">jo&lt;<span class="hljs-regexp">/mark&gt;ur, mois, annee) {
    return new Date(annee, mois - 1, jour);
}</span></span></span>
```

**highlight.js with `<mark>`**

```js
const code = `// fonction pour créer un objet date
function gjsCreer<mark>ObjetDate(jo</mark>ur, mois, annee) {
    return new Date(annee, mois - 1, jour);
}`;
console.log(hljs.highlight('javascript', code).value);
```

```html
// fonction pour créer un objet date
function gjsCreer&lt;mark&gt;ObjetDate(jo&lt;/mark&gt;ur, mois, annee) {
    return new Date(annee, mois - 1, jour);
}
```

---

With all of this in mind, let me think a bit about whether or not to support this behavior and add a `highlightBlock()` equivalent in highlight.php.

In *my* opinion, embedding HTML in a code snippet to bring emphasis to something isn't the way to do things. I personally would make a preprocessor to take special markup, remove it, highlight it, and have a postprocessor reinsert the markup. But that is beyond the scope of this project. Using `splitCodeIntoArray()` as an example, the way it works is we highlight everything, then split it up, and then render it in a table or div.

**Comment by taufik-nurrohman** [comment] 2020-01-26 06:00
Maybe this behaviour can be resolved by detecting whether the input is already escaped or not to tell the parser to escape input before proccessing or not (or simply add an option to disable auto-escape the input). But as this project really depends on the _highlight.js_ specification then I can&rsquo;t do anything.

Most of code snippet highlighted with _highlight.js_ must be escaped because without escaping it, we will end up with broken HTML markup whenever JavaScript is disabled.

**Comment by taufik-nurrohman** [comment] 2020-01-26 06:19
> With all of this in mind, let me think a bit about whether or not to support this behavior and add a `highlightBlock()` equivalent in _highlight.php_.

Would be good if we can leave the `DOMDocument` stuff from this.

Here are some specs:

### Before

~~~ .html
abcd <a>"efgh"</a> ijk
~~~

### After

~~~ .html
abcd <a><span class="hljs-string">"efgh"</span></a> ijk
~~~

or:

~~~ .html
abcd <span class="hljs-string"><a>"efgh"</a></span> ijk
~~~

### Before

~~~ .html
ab<a>cd "ef</a>gh" ijk
~~~

### After

~~~ .html
ab<a>cd </a><span class="hljs-string"><a>"ef</a>gh"</span> ijk
~~~

**Comment by allejo** [comment] 2020-01-26 06:24
> Maybe this behaviour can be resolved by detecting whether the input is already escaped or not to tell the parser to escape input before proccessing it or not (or simply add an option to disable auto-escape the input). But as this project really depends on the _highlight.js_ specification then I can’t do anything.

It's not that escaping is the problem, it's how to handle an entirely different language during the highlighting. Let's take a language with generics (TypeScript) as an example:

```typescript
function doSomething<T>(arg: T, accuracy: number) {}
```

Because highlight.js works in the browser with a DOM, you can have actual HTML elements in the mix but if you're using highlight.js via Node, you can't easily.

Let's say you want to highlight "doSomething" in this example. You have two options:

**Without escaping**

```typescript
function <mark>doSomething</mark><T>(arg: T, accuracy: number) {}
```

**With escaping**

```typescript
function &lt;mark%gt;doSomething&lt;/mark&gt;<T>(arg: T, accuracy: number) {}
```

Regardless of whether or not you escape the incoming text, that won't change the fact that our highlighter will not know how to handle `mark` when told to highlight this code snippet as `typescript`.

`highlight()` both in JS and PHP only accept strings and don't have an understanding of DOM nodes. My understanding is when using something like `highlightBlock`, DOM nodes are taken into account.

This is why I feel a pre+post-processor would be needed so whenever `highlight()` is called, it's **only** highlighting valid TypeScript code (like in the example above). The pre-processor would remove the custom HTML and the post-processor would reinsert it.

**Comment by taufik-nurrohman** [comment] 2020-01-26 06:42
Just got an idea. For the preprocessor, I can store the HTML tag match offset using `preg_split()` and `PREG_SPLIT_OFFSET_CAPTURE` flag. In the process, I can remove the HTML tags, after process, I can then restore back the splitted HTML tags based on its captured offset data using certain method.

~~~ .php
$tokens = preg_split('/<[^>]+>/', $input, null, PREG_SPLIT_OFFSET_CAPTURE);
$out = $hl->highlight('html', strip_tags($input));

$out->value = post_process($out->value, $tokens);
// Etc.
~~~

**Comment by allejo** [comment] 2020-01-26 07:08
Sure that could possibly work. Just make sure you take into consideration that your offsets will be different from the original source code since `highlight()` will return all the extra span tags.

**Comment by allejo** [comment] 2020-01-27 08:32
After thinking about this further, I'm unable to come up with a solution that would work robustly across multiple languages and scenarios. Right now, both highlight.js and highlight.php take in unescaped code (e.g. HTML, XML, languages with generics) and will auto-escape them during the highlighting process and return valid HTML. I feel like introducing a function like `highlightBlock` to highlight.php would introduce confusion on how to give code as a parameter (escaped or unescaped), what markup would allow for highlighting lines (e.g. should it be XML?), how to add links inside of code, etc. It's unreliable to [parse HTML/XML with regular expressiones](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags), so while it may work in your use case, it won't guarantee it'll work in others.

I'm open to revisiting this topic if someone has a robust way of handling this problem and including it in the `HighlightUtilities` namespace. Until then, I'll close this issue as "won't fix" and leave my suggestion as: implement this functionality in your projects on top of highlight.php with a pre+post-processor.

**Closed by allejo** 2020-01-27 08:32 UTC
Labels: enhancement, under consideration
